### ISSUE TITLE
Add chat message to reduce support traffic

### ISSUE THREAD

**Issue by YvesW** [WaylonJ/OSRS_ClickToMinimize#3]
Could you add a chat message when the client gets minimized because of your plugin? That reduces support traffic like https://discord.com/channels/301497432909414422/419891709883973642/1282709945984352267

The message should:
- Clearly mention that the client was minimized by the click to minimize plugin
- Probably have a config option that's enabled by default but can be disabled
- Have a cooldown. E.g. you can get the nanoTime when you previously sent the message and compare it to the nanoTime when trying to minimize again. If the difference is > cooldown -> send chat message.
- If your plugin also works on the login screen, you'll have to set a flag to send a message in the GameTick event and consume the flag then, but the plugin probs doesn't work on the login screen.

**Comment by WaylonJ** [comment]
PR created here to address this issue:
https://github.com/runelite/plugin-hub/pull/6573

**Comment by YvesW** [comment]
Thanks! I'll close the issue as a chatmessage has been added, but I've left some tips here https://discord.com/channels/301497432909414422/334801290645209099/1282768078094077995 after I quickly scanned your code
